version: '2'

services:
# apigw service
  apigw:
    image: cloudstore-go/apigw
    networks:
      - web
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
    labels:
      - "traefik.backend=apigw"
      - "traefik.frontend.rule=Host:apigw.cloudstore-go.com" # TODO
      - "traefik.docker.port=8080"
# upload service
  upload:
    image: cloudstore-go/upload
    networks:
      - web
    volumes:
      - /data/fileserver:/data/fileserver
      - /data/fileserver_part:/data/fileserver_part
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
    labels:
      - "traefik.backend=upload"
      - "traefik.frontend.rule=Host:upload.fileserver.com"
      - "traefik.docker.port=28080"
# download service
  download:
    image: hub.fileserver.com/filestore/download
    networks:
      - web
    volumes:
      - ./db:/data/master
      - ./db_slave:/data/slave
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
    labels:
      - "traefik.backend=download"
      - "traefik.frontend.rule=Host:download.fileserver.com"
      - "traefik.docker.port=38080"
# account service
  account:
    image: hub.fileserver.com/filestore/account
    networks:
      - web
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
# transfer service
  transfer:
    image: cloudstorer-go/transfer
    networks:
      - web
    volumes:
      - ./db:/data
      - ./db_slave:/data/slave
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
# dbproxy service
  dbproxy:
    image: cloudstore-go/dbproxy
    networks:
      - web
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
networks:
  web:
    external:
      name: cloudstore-go